version: '3.8'

services:
  #database section 
        
  #Members: mysql
  memberdb:
    container_name: memberdb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  coursedb:
    container_name: coursedb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  
  #infrastructure section 
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  #microservices api section
  user-service:
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=memberdb;Port=3306;Database=Members;Uid=root;Pwd=Passw0rd!"
    depends_on: 
      - memberdb
    ports:
      - "6002:80"
    restart: always