version: '3.8'

services:
  #database section
  memberdb:
    image: mysql:8.0.29
  coursedb:
    image: mysql:8.0.29

  #infrastructure section
  portainer:
    image: portainer/portainer-ce   
  #microservices api section
  user-service:
    image: ${DOCKER_REGISTRY-}user-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: User-service/Dockerfile
#network section
networks:
  default:
    name: netcore_training
    driver: bridge

#volumes section
volumes:
  mysql_data:
    name: mysql_data
  portainer_data:
    name: portainer_data
