version: '3.8'

services:
  #database section 
        
  #Members: mysql
  mysqldb:
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" 
  #infrastructure section 
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  #microservices api section
  user-service:
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=mysqldb;Port=3306;Database=Members;Uid=root;Pwd=Passw0rd!"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - mysqldb
      - rabbitmq
    ports:
      - "6002:80"
    restart: always
  course-service:
    container_name: course-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=mysqldb;Port=3306;Database=Course;Uid=root;Pwd=Passw0rd!"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "UserServiceAddress=http://172.16.20.229:6002"
      - "RetryCount=3"
      - "RetryAttemptSeconds=5"
    depends_on: 
      - mysqldb
      - rabbitmq
    ports:
      - "6003:80"
    restart: always
    #-http://172.16.20.229: Your PC IP Address