version: '3.8'

services:
  #database section 
        
  #DotnetCoreTraining: mysql
  DotnetCoreTraining:
    container_name: DotnetCoreTraining
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  #infrastructure section
    
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
